### ISSUE TITLE
Installation guide for multiple platforms

### ISSUE THREAD

**Issue by v0idpwn** [tembo-io/pgmq#238]
```[tasklist]
### Tasks
- [ ] Guide for PGXN
- [ ] Guide for Windows
- [ ] Guide for Mac
```

**Comment by ChuckHend** [comment]
@v0idpwn , I think now that this is pl/pgsql we would just need to add instructions for windows? `make install` pretty much does everything now.

**Comment by nyarly** [comment]
For reference, I bounced off of pgmq because all the documentation for getting started was "run this Docker image" - I already have a postgresql instance, and I'm not interested in dockerizing it.

Unless there's clear, standalone install instructions for pgmq, I'm not interested.

**Comment by theory** [comment]
Probably worth adding a few options to the README:

``` sh
pgxn install pgmq
```

Or:

``` sh
curl -LO https://api.pgxn.org/dist/pgmq/1.4.2/pgmq-1.4.2.zip
unzip pgmq-1.4.2.zip
cd pgmq-1.4.2
make
make install
```

**Comment by nyarly** [comment]
Okay, but what's `pgxn`?

**Comment by theory** [comment]
> PGXN, the PostgreSQL Extension network, is a central distribution system for open-source PostgreSQL extension libraries.

— [About PGXN](https://pgxn.org/about/)
